# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-04-12 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0003_auto_20160408_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_jianzhi',
            name='shi_jian',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='post_jianzhi',
            name='shi_jian2',
            field=models.DateTimeField(),
        ),
    ]
