# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-05-04 11:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0006_auto_20160504_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_jianzhi',
            name='date_time',
            field=models.CharField(default=datetime.datetime(2016, 5, 4, 19, 25, 9, 806524), max_length=100),
        ),
    ]
