# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-05-04 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0009_auto_20160504_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_jianzhi',
            name='date_time',
        ),
        migrations.AlterField(
            model_name='post_jianzhi',
            name='timer',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
