# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-04-07 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post_jianzhi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('jian_jie', models.CharField(max_length=300)),
                ('jing_er', models.IntegerField()),
                ('di_zhi', models.CharField(max_length=30)),
                ('shi_jian', models.DateField()),
                ('shi_jian2', models.DateField()),
                ('lxfs', models.CharField(max_length=50)),
                ('timer', models.DateTimeField(auto_now_add=True)),
                ('area', models.CharField(choices=[('sq', '石岐'), ('dq', '东区'), ('xq', '西区'), ('nq', '南区'), ('wgs', '五桂山'), ('hjkfq', '火炬开发区'), ('hp', '黄埔'), ('nt', '南头'), ('df', '东凤'), ('fs', '阜沙'), ('xl', '小榄'), ('ds', '东升'), ('gz', '古镇'), ('hl', '横栏'), ('sj', '三角'), ('mz', '民众'), ('nl', '南朗'), ('gk', '港口'), ('dz', '大涌'), ('sha_xi', '沙溪'), ('san_xiang', '三乡'), ('bf', '板芙'), ('sw', '神湾'), ('tz', '坦洲')], max_length=30)),
                ('day_hw', models.CharField(choices=[('/天', '/天'), ('/时', '/时')], max_length=10)),
                ('zhao_ping', models.IntegerField()),
                ('jie_suan', models.CharField(choices=[('完工结算', '完工结算'), ('每天结算', '每天结算'), ('每周结算', '每周结算'), ('每月结算', '每月结算')], max_length=10)),
            ],
        ),
    ]
