# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-04-08 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0002_auto_20160408_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_jianzhi',
            name='area',
            field=models.CharField(choices=[('sq', '石岐'), ('dq', '东区'), ('xq', '西区'), ('nq', '南区'), ('wgs', '五桂山'), ('hjkfq', '火炬开发区'), ('hp', '黄埔'), ('nt', '南头'), ('df', '东凤'), ('fs', '阜沙'), ('xl', '小榄'), ('ds', '东升'), ('gz', '古镇'), ('hl', '横栏'), ('sj', '三角'), ('mz', '民众'), ('nl', '南朗'), ('gk', '港口'), ('dz', '大涌'), ('sha_xi', '沙溪'), ('san_xiang', '三乡'), ('bf', '板芙'), ('sw', '神湾'), ('tz', '坦洲')], max_length=30),
        ),
        migrations.AlterField(
            model_name='post_jianzhi',
            name='day_hw',
            field=models.CharField(choices=[('/天', '/天'), ('/时', '/时')], max_length=10),
        ),
        migrations.AlterField(
            model_name='post_jianzhi',
            name='jie_suan',
            field=models.CharField(choices=[('完工结算', '完工结算'), ('每天结算', '每天结算'), ('每周结算', '每周结算'), ('每月结算', '每月结算')], max_length=10),
        ),
    ]
