# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-04-18 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0004_auto_20160412_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_jianzhi',
            name='shi_jian',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='post_jianzhi',
            name='shi_jian2',
            field=models.CharField(max_length=10),
        ),
    ]
