# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-05-04 09:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0005_auto_20160418_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_jianzhi',
            name='date_time',
            field=models.CharField(default=datetime.datetime(2016, 5, 4, 9, 56, 55, 956733, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post_jianzhi',
            name='timer',
            field=models.CharField(default='2016 05 04', max_length=100),
        ),
    ]
