# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-05-04 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0008_auto_20160504_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_jianzhi',
            name='timer',
            field=models.CharField(default='2016-05-04', max_length=100),
        ),
    ]
