# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-05-04 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0010_auto_20160504_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_jianzhi',
            name='day_hw',
            field=models.CharField(choices=[('元/天', '元/天'), ('元/时', '元/时')], max_length=10),
        ),
    ]
